// All user-facing widget text, in every language the site speaks.
// The page's <html lang> attribute picks the dictionary; the essay prose
// itself lives in the HTML (index.html / de/index.html).

const isDe = (document.documentElement.lang || "en").toLowerCase().startsWith("de");

// Display-number formatter: German readers expect a decimal comma.
// Geometry code keeps using model.js fmt() — never localize path data.
const nEn = (v, d = 1) => v.toFixed(d);
const nDe = (v, d = 1) => v.toFixed(d).replace(".", ",");

const en = {
  n: nEn,
  kn: "kn",
  sides: { starboard: "starboard", port: "port" },

  pos: {
    nogo: "In irons — the no-go zone",
    closehauled: "Close-hauled",
    closereach: "Close reach",
    beamreach: "Beam reach",
    broadreach: "Broad reach",
    run: "Run",
  },

  apparent: {
    trueWindNote: "true wind",
    vecTrue: "true wind",
    vecBoat: "wind you make",
    vecApparent: "apparent wind",
    slBoatSpeed: "Boat speed",
    slTrueWind: "True wind",
    roTrue: "True wind",
    roBoat: "Boat speed",
    roApparent: "Apparent wind",
    roAngle: "Apparent angle",
    msgStopped: "The boat is stopped, so the apparent wind <em>is</em> the true wind. Speed up and watch them split apart.",
    msgNoGo: "Pointing almost dead upwind: your own motion just adds to the true wind on the nose. Sails can’t work here — this is the no-go zone.",
    msgRun: (aws) => `Running downwind, your boat speed <em>subtracts</em>: only ${aws} kn of apparent wind is left to work with. This is why dead downwind feels calm — and is slow.`,
    msgForward: (shift, aws) => `The apparent wind has swung ${shift}° <em>forward</em> of the true wind and blows at ${aws} kn. The faster you go, the more wind seems to come from ahead.`,
    msgGeneral: (tws, twa, bsp, aws, awa) => `True wind ${tws} kn at ${twa}° off the bow; moving at ${bsp} kn bends it to ${aws} kn at ${awa}°. The sail only ever meets this teal vector.`,
  },

  sail: {
    noteLine1: "apparent",
    noteLine2: "wind →",
    vecLift: "lift",
    vecDrag: "drag",
    vecTotal: "total force",
    chartLift: "lift",
    chartDrag: "drag",
    slAoa: "Angle of attack",
    roCl: "Lift coefficient",
    roCd: "Drag coefficient",
    roLd: "Lift ÷ drag",
    chipLuffing: "Luffing",
    chipStalled: "Stalled",
    chipEdge: "On the edge",
    chipDrawing: "Drawing",
    msgLuffing: "The sail is edge-on to the wind: the cloth flogs like a flag and produces almost nothing. This is what “letting the sail out too far” feels like.",
    msgStalled: "Sheeted in too hard: the flow can no longer follow the lee side and tears away into eddies. Lift collapses, drag balloons — the sail becomes a barn door.",
    msgEdge: "Right at the stall. Racers trim here on purpose — maximum force — but a small gust or wobble tips the flow into separation.",
    msgDrawing: (ld) => `Smooth attached flow. The sail bends the wind, the wind pushes back: ${ld}× more lift than drag. This is a wing, standing upright.`,
  },

  points: {
    trueWindNote: "true wind",
    ring: {
      nogo: "no-go zone", closehauled: "close-hauled", closereach: "close reach",
      beamreach: "beam reach", broadreach: "broad reach", run: "run",
    },
    vecApparent: "apparent wind",
    vecForce: "sail force",
    vecDrive: "drive",
    vecHeel: "heel",
    meterDrive: "Drive (forward)",
    meterHeel: "Heel (sideways)",
    roTwa: "True wind angle",
    roBsp: "Boat speed",
    roAws: "Apparent wind",
    roSheet: "Sheet angle",
    msgNoGo: "Head to wind: even fully sheeted in, the sail can’t meet the wind at a working angle. It luffs, the boat stops. To go this way you must zig-zag — <em>tack</em> — across the zone.",
    msgCloseHauled: "Close-hauled: the sail is working hard, but the force points mostly <em>sideways</em>. The keel turns that sideways shove into forward motion — at the price of heeling. This is as close to the wind as physics allows.",
    msgReach: "Reaching: the force vector has rotated forward. Lots of drive, tolerable heel, and the apparent wind is still strong — this is the fast lane.",
    msgBroad: "Broad reach: still mostly lift-driven and quick, though your own speed is now stealing apparent wind. Racers live here downwind.",
    msgRun: "Running: the boom is all the way out and the sail is just a parachute — pure drag, no lift. It works, but weakly: notice how little apparent wind is left.",
  },

  polar: {
    upwind: "↑ upwind",
    downwind: "↓ downwind",
    nogo: "no-go",
    curveLabel: (tws) => `${tws} kn wind`,
    bestUp: "best VMG upwind",
    bestDown: "best VMG downwind",
    vmg: "VMG",
    chip: (tws) => `${tws} kn`,
    chipGroup: "True wind speed",
    roTwa: "Wind angle",
    roBsp: "Boat speed",
    roVmg: "VMG",
    vmgUp: (v) => `${v} kn upwind`,
    vmgDown: (v) => `${v} kn downwind`,
    msgNoGo: "Inside the no-go zone the polar collapses to zero — the sail can’t work here. The route upwind is the pair of dots: sail close-hauled, tack, repeat.",
    msgBestUp: (a, vmg) => `The upwind groove: ${a}° isn’t the closest you can point, but it’s the angle that makes the most progress <em>toward</em> the wind — ${vmg} kn of VMG.`,
    msgDeadRun: (v, a, gain) => `Dead downwind: ${v} kn. But heat it up to ${a}° and gybe your way there instead — the extra boat speed beats the longer path by about ${gain}%.`,
    msgFat: (isBeam) => `The fat part of the polar. Around here the apparent wind is still strong and fully usable — this is why a ${isBeam ? "beam" : "broad"} reach is the fastest point of sail.`,
    msgGeneral: (twa, tws, v) => `At ${twa}° in ${tws} kn of wind this boat makes ${v} kn. Drag around the curve, and try the other wind speeds — notice how the curves bunch up as the hull runs out of waterline.`,
  },

  mob: {
    btnPort: "⟲ port",
    btnStarboard: "starboard ⟳",
    btnRestart: "restart",
    roBsp: "Boat speed",
    roTwa: "Wind angle",
    roDist: "Distance to crew",
    roClock: "Clock",
    bannerAlarm: "Crew overboard!",
    bannerSaved: (mmss) => `Crew recovered — ${mmss} in the water`,
    msgSailing: "You’re on a beam reach in 12 kn of breeze. Get a feel for the helm with ← and → (or the buttons). Notice you simply cannot steer straight upwind.",
    msgSaved: "Well sailed. The trick you just used — arrive <em>pointing close to the wind</em>, so the sail can spill its power and the boat parks — is exactly the apparent-wind physics from the top of this page.",
    msgIrons: "You’re in irons — stuck head to wind, sails luffing, speed bleeding away. Bear away to either side to fill the sail again.",
    msgTooFast: "Close now, but too fast — at this speed you’ll overshoot the swimmer. Head up toward the wind to slow down.",
    msgGeneral: (v) => `Get back to the swimmer, then arrive <em>slowly</em>: within the dashed circle at under ${v} kn. Classic shape: sail off on a beam reach, turn, come back on a close reach so you can slow down at will.`,
  },
};

const de = {
  n: nDe,
  kn: "kn",
  sides: { starboard: "Steuerbord", port: "Backbord" },

  pos: {
    nogo: "Im Wind — tote Zone",
    closehauled: "Hoch am Wind",
    closereach: "Am Wind",
    beamreach: "Halbwindkurs",
    broadreach: "Raumschotskurs",
    run: "Vorwindkurs",
  },

  apparent: {
    trueWindNote: "wahrer Wind",
    vecTrue: "wahrer Wind",
    vecBoat: "Fahrtwind",
    vecApparent: "scheinbarer Wind",
    slBoatSpeed: "Fahrt",
    slTrueWind: "Wahrer Wind",
    roTrue: "Wahrer Wind",
    roBoat: "Fahrt",
    roApparent: "Scheinbarer Wind",
    roAngle: "Scheinbarer Winkel",
    msgStopped: "Das Boot liegt still, also <em>ist</em> der scheinbare Wind der wahre Wind. Nimm Fahrt auf und sieh zu, wie die beiden auseinanderlaufen.",
    msgNoGo: "Fast genau gegenan: Die eigene Fahrt addiert sich nur zum Wind auf der Nase. Segel können hier nicht arbeiten — das ist die tote Zone.",
    msgRun: (aws) => `Vor dem Wind zieht sich die eigene Fahrt <em>ab</em>: Nur ${aws} kn scheinbarer Wind bleiben zum Arbeiten übrig. Deshalb fühlt sich platt vorm Wind alles so ruhig an — und ist so langsam.`,
    msgForward: (shift, aws) => `Der scheinbare Wind ist ${shift}° <em>vorlicher</em> als der wahre Wind und weht mit ${aws} kn. Je schneller du wirst, desto mehr scheint der Wind von vorn zu kommen.`,
    msgGeneral: (tws, twa, bsp, aws, awa) => `Wahrer Wind: ${tws} kn, ${twa}° zum Bug. Bei ${bsp} kn Fahrt wird daraus ${aws} kn aus ${awa}°. Das Segel kennt immer nur diesen türkisen Vektor.`,
  },

  sail: {
    noteLine1: "scheinbarer",
    noteLine2: "Wind →",
    vecLift: "Auftrieb",
    vecDrag: "Widerstand",
    vecTotal: "Gesamtkraft",
    chartLift: "Auftrieb",
    chartDrag: "Widerstand",
    slAoa: "Anstellwinkel",
    roCl: "Auftriebsbeiwert",
    roCd: "Widerstandsbeiwert",
    roLd: "Auftrieb ÷ Widerstand",
    chipLuffing: "Killt",
    chipStalled: "Abgerissen",
    chipEdge: "Auf der Kante",
    chipDrawing: "Zieht",
    msgLuffing: "Das Segel steht mit der Kante im Wind: Das Tuch killt wie eine Flagge und erzeugt fast nichts. Genau so fühlt sich „zu weit gefiert“ an.",
    msgStalled: "Zu dicht geholt: Die Strömung kann der Leeseite nicht mehr folgen und reißt in Wirbeln ab. Der Auftrieb bricht ein, der Widerstand bläht sich auf — das Segel wird zum Scheunentor.",
    msgEdge: "Genau an der Abrisskante. Regattasegler trimmen mit Absicht hierhin — maximale Kraft —, aber eine kleine Bö oder ein Ruckler kippt die Strömung in den Abriss.",
    msgDrawing: (ld) => `Glatt anliegende Strömung. Das Segel lenkt den Wind um, der Wind drückt zurück: ${ld}-mal mehr Auftrieb als Widerstand. Das ist ein Flügel — hochkant gestellt.`,
  },

  points: {
    trueWindNote: "wahrer Wind",
    ring: {
      nogo: "tote Zone", closehauled: "hoch am Wind", closereach: "am Wind",
      beamreach: "halber Wind", broadreach: "raumschots", run: "vor dem Wind",
    },
    vecApparent: "scheinbarer Wind",
    vecForce: "Segelkraft",
    vecDrive: "Vortrieb",
    vecHeel: "Krängung",
    meterDrive: "Vortrieb (voraus)",
    meterHeel: "Krängung (seitlich)",
    roTwa: "Wahrer Windwinkel",
    roBsp: "Fahrt",
    roAws: "Scheinbarer Wind",
    roSheet: "Schotwinkel",
    msgNoGo: "Im Wind: Selbst ganz dichtgeholt findet das Segel keinen Arbeitswinkel. Es killt, das Boot bleibt stehen. In diese Richtung geht es nur im Zickzack — durch <em>Wenden</em> quer über die Zone.",
    msgCloseHauled: "Hoch am Wind: Das Segel arbeitet hart, aber die Kraft zeigt vor allem <em>zur Seite</em>. Der Kiel macht aus dem seitlichen Schub Vortrieb — zum Preis der Krängung. Dichter an den Wind lässt die Physik nicht.",
    msgReach: "Halbwind: Der Kraftvektor hat nach vorn gedreht. Viel Vortrieb, erträgliche Krängung, und der scheinbare Wind ist noch stark — die Überholspur.",
    msgBroad: "Raumschots: immer noch schnell und vom Auftrieb getragen, aber die eigene Fahrt stiehlt jetzt scheinbaren Wind. Regattasegler segeln Vorwindstrecken genau hier.",
    msgRun: "Vorwindkurs: Der Baum ist ganz gefiert, das Segel nur noch ein Fallschirm — reiner Widerstand, kein Auftrieb. Es funktioniert, aber schwach: Sieh, wie wenig scheinbarer Wind übrig bleibt.",
  },

  polar: {
    upwind: "↑ gegen den Wind",
    downwind: "↓ vor dem Wind",
    nogo: "tote Zone",
    curveLabel: (tws) => `${tws} kn Wind`,
    bestUp: "bestes VMG in Luv",
    bestDown: "bestes VMG in Lee",
    vmg: "VMG",
    chip: (tws) => `${tws} kn`,
    chipGroup: "Wahre Windgeschwindigkeit",
    roTwa: "Windwinkel",
    roBsp: "Fahrt",
    roVmg: "VMG",
    vmgUp: (v) => `${v} kn gegen den Wind`,
    vmgDown: (v) => `${v} kn vor dem Wind`,
    msgNoGo: "In der toten Zone fällt die Polare auf null — das Segel kann hier nicht arbeiten. Der Weg nach Luv führt über die beiden Punkte: hoch am Wind segeln, wenden, wiederholen.",
    msgBestUp: (a, vmg) => `Der Aufkreuz-Sweetspot: ${a}° ist nicht der spitzeste segelbare Winkel, aber der mit dem meisten Fortschritt <em>gegen</em> den Wind — ${vmg} kn VMG.`,
    msgDeadRun: (v, a, gain) => `Platt vor dem Wind: ${v} kn. Luv stattdessen auf ${a}° an und halse dich ans Ziel — die Mehrfahrt schlägt den längeren Weg um rund ${gain} %.`,
    msgFat: (isBeam) => `Der Bauch der Polare. Hier ist der scheinbare Wind noch stark und voll nutzbar — deshalb ist der ${isBeam ? "Halbwind" : "Raumschots"}kurs der schnellste Kurs.`,
    msgGeneral: (twa, tws, v) => `Bei ${twa}° und ${tws} kn Wind läuft dieses Boot ${v} kn. Zieh am Diagramm entlang und probiere die anderen Windstärken — sieh, wie sich die Kurven bündeln, wenn dem Rumpf die Wasserlinie ausgeht.`,
  },

  mob: {
    btnPort: "⟲ Backbord",
    btnStarboard: "Steuerbord ⟳",
    btnRestart: "Neustart",
    roBsp: "Fahrt",
    roTwa: "Windwinkel",
    roDist: "Abstand zur Person",
    roClock: "Uhr",
    bannerAlarm: "Mensch über Bord!",
    bannerSaved: (mmss) => `Person geborgen — ${mmss} im Wasser`,
    msgSailing: "Du segelst Halbwindkurs bei 12 kn Wind. Bekomm mit ← und → (oder den Tasten) ein Gefühl fürs Ruder. Merkst du, dass du nicht direkt gegen den Wind steuern kannst?",
    msgSaved: "Gut gesegelt. Der Trick von eben — <em>nah am Wind ankommen</em>, damit das Segel seine Kraft loswerden kann und das Boot parkt — ist genau die Physik des scheinbaren Windes vom Anfang dieser Seite.",
    msgIrons: "Du stehst im Wind — Segel killen, die Fahrt schwindet. Fall nach einer Seite ab, damit das Segel wieder zieht.",
    msgTooFast: "Fast da, aber zu schnell — so schießt du über die Person hinweg. Luv an, um Fahrt wegzunehmen.",
    msgGeneral: (v) => `Zurück zur Person im Wasser, dann <em>langsam</em> ankommen: innerhalb des gestrichelten Kreises mit weniger als ${v} kn. Der Klassiker: mit Halbwind weg, drehen, hoch am Wind zurück — dann kannst du jederzeit bremsen.`,
  },
};

export const S = isDe ? de : en;
